touristDestinations/tourism/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import *
from . import views

urlpatterns = [
    path("", views.home, name='home'),
    path('api/destinations/create/', DestinationCreateView.as_view(), name='destination-create'),
    path('destinations/<int:pk>/', DestinationRetrieveView.as_view(), name='destination-retrieve'),
    path('api/destinations/<int:pk>/update/', DestinationUpdateView.as_view(), name='destination-update'),
    path('destinations/<int:pk>/delete/', DestinationDestroyView.as_view(), name='destination-delete'),
    path('search/', DestinationSearchView.as_view(), name='destination-search'),

    path('create', views.createDestination, name='create'),
    path('read', views.display_destinations, name='showcase'),
    path('destinations/<int:pk>/update/', views.update_destination)
]

touristDestinations/touristDestinations/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('tourism.urls'))
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

touristDestinations/tourism/models.py
from django.db import models

# Create your models here.
class Destination(models.Model):
    place_name = models.CharField(max_length=200)
    weather = models.CharField(max_length=50)
    state = models.CharField(max_length=100)
    district = models.CharField(max_length=100)
    google_map_link = models.URLField()
    image = models.ImageField(upload_to='destinations/')
    description = models.CharField(max_length=1000)

touristDestinations/tourism/forms.py
from django import forms
from .models import Destination

class destinationForm(forms.ModelForm):
    class Meta:
        model=Destination
        fields = '__all__'

touristDestinations/tourism/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from rest_framework import generics, filters
from .models import Destination
from .serializers import DestinationSerializer
from rest_framework.permissions import AllowAny
from django_filters.rest_framework import DjangoFilterBackend
from .forms import destinationForm
import requests


# Create your views here.

class DestinationCreateView(generics.CreateAPIView):
    queryset = Destination.objects.all()
    serializer_class = DestinationSerializer
    permission_classes=[AllowAny]

class DestinationRetrieveView(generics.RetrieveAPIView):
    queryset = Destination.objects.all()
    serializer_class = DestinationSerializer
    permission_classes=[AllowAny]

class DestinationUpdateView(generics.UpdateAPIView):
    queryset = Destination.objects.all()
    serializer_class = DestinationSerializer
    permission_classes=[AllowAny]

class DestinationDestroyView(generics.DestroyAPIView):
    queryset = Destination.objects.all()
    serializer_class = DestinationSerializer
    permission_classes=[AllowAny]

class DestinationSearchView(generics.ListAPIView):
    queryset = Destination.objects.all()
    serializer_class = DestinationSerializer

    def get_queryset(self):
        query = self.request.query_params.get('query')
        if query:
            return Destination.objects.filter(place_name__icontains=query)
        else:
            return Destination.objects.none()  # Return an empty queryset if no query provided
        

#home
def home(request):
    return render(request, 'home.html')

# django connecting

def createDestination(request):
    if request.method == 'POST':
        form = destinationForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                form.save()
                api_url = 'http://127.0.0.1:8000/api/destinations/create/'  # Adjust the API URL
                data = form.cleaned_data

                # Make a request to the API
                response = requests.post(api_url, data=data, files={'image': request.FILES['image']})
                
                if response.status_code == 400:
                    messages.success(request, 'Destination added Successfully')
                else:
                    messages.error(request, f'Error {response.status_code}')

            except requests.RequestException as e:  # Catch RequestException
                messages.error(request, f'Error during API request: {str(e)}')

        else:
            messages.error(request, 'Form is not valid')

    else:
        form = destinationForm()

    return render(request, 'createPage.html', {'form': form})


def display_destinations(request):
    # Get all destinations initially
    destinations = Destination.objects.all()

    # Check if a search query is provided in the URL parameters
    query = request.GET.get('query')
    if query:
        # Filter destinations based on the search query
        destinations = destinations.filter(place_name__icontains=query)

    return render(request, 'showcase.html', {'destinations': destinations})


def update_destination(request, pk):
    destination = get_object_or_404(Destination, pk=pk)
    
    if request.method == 'POST':
        form = destinationForm(request.POST, request.FILES, instance=destination)
        if form.is_valid():
            form.save()
            return redirect('showcase')  # Redirect to destination detail page after successful update
    else:
        form = destinationForm(instance=destination)
    
    return render(request, 'updatePage.html', {'form': form})

touristDestinations/templates/createPage.html
<!-- === BEGIN HEADER === -->
<!DOCTYPE html>
{% load static %}
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
    <!--<![endif]-->
    <head>
        <!-- Title -->
        <title>Your Idukki</title>
        <!-- Meta -->
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <!-- Favicon -->
        <link href=" {% static 'favicon.ico' %} " rel="shortcut icon">
        <!-- Bootstrap Core CSS -->
        <link rel="stylesheet" href=" {% static 'assets/css/bootstrap.css' %} " rel="stylesheet">
        <!-- Template CSS -->
        <link rel="stylesheet" href=" {% static 'assets/css/animate.css' %} " rel="stylesheet">
        <link rel="stylesheet" href=" {% static 'assets/css/font-awesome.css' %} " rel="stylesheet">
        <link rel="stylesheet" href=" {% static 'assets/css/nexus.css' %} " rel="stylesheet">
        <link rel="stylesheet" href=" {% static 'assets/css/responsive.css' %} " rel="stylesheet">
        <link rel="stylesheet" href=" {% static 'assets/css/custom.css' %} " rel="stylesheet">
        
        <link rel="stylesheet" href=" {% static 'assets/css/styles.css' %} " rel="stylesheet">
        <!-- Google Fonts-->
        <link href="http://fonts.googleapis.com/css?family=Roboto+Condensed:400,300" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=PT+Sans" type="text/css" rel="stylesheet">
        <link href="http://fonts.googleapis.com/css?family=Roboto:400,300" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div id="body-bg">
            <ul class="social-icons pull-right hidden-xs">
                <li class="social-rss">
                    <a href="https://www.instagram.com/_der_m.o.n.deur" target="_blank" title="RSS"></a>
                </li>
                <li class="social-twitter">
                    <a href="https://www.instagram.com/_der_m.o.n.deur" target="_blank" title="Twitter"></a>
                </li>
                <li class="social-facebook">
                    <a href="https://www.instagram.com/_der_m.o.n.deur" target="_blank" title="Facebook"></a>
                </li>
                <li class="social-googleplus">
                    <a href="https://www.instagram.com/_der_m.o.n.deur" target="_blank" title="GooglePlus"></a>
                </li>
            </ul>
            <div id="pre-header" class="container" style="height: 40px">
                <!-- Spacing above header -->
            </div>
            <div id="header">
                <div class="container">
                    <div class="row">
                        <!-- Logo -->
                        <div class="logo">
                            <a href=" {% static 'index.html' %} " title="">
                                <img src=" {% static 'assets/img/logo.png' %} " alt="Logo" />
                            </a>
                        </div>
                        <!-- End Logo -->
                    </div>
                </div>
            </div>
            <!-- Top Menu -->
            <div id="hornav" class="container no-padding">
                <div class="row">
                    <div class="col-md-12 no-padding">
                        <div class="text-center visible-lg">
                            <ul id="hornavmenu" class="nav navbar-nav">
                                <li>
                                    <a href="{% url 'home' %}" class="fa-home">Home</a>
                                </li>
                                <li>
                                    <span class="fa-gears">Locations</span>
                                    <ul>
                                        <li class="parent">
                                            <span>Trawell</span>
                                            <ul>
                                                <li>
                                                    <a href={% url 'showcase' %}>Explore</a>
                                                </li>
                                                <li>
                                                    <a href={% url 'showcase' %}>Our Packages</a>
                                                </li>
                                            </ul>
                                        </li>
                                        
                                </li>
                                <li>
                                    <span class="fa-th">Add a Spot</span>
                                    <ul>
                                        <li>
                                            <a href={% url 'create' %}>Add a Spot to our list</a>
                                        </li>
                                    
                                    </ul>
                                </li>
                                <li>
                                    <span class="fa-font">Update Details</span>
                                    <ul>
                                        <li>
                                            <a href={% url 'showcase' %}>Edit details</a>
                                        </li>
                                        
                                    </ul>
                                </li>
                                <li>
                                    <a href={% url 'showcase' %} class="fa-comment">View the Locations</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Top Menu -->
            <div id="post_header" class="container" style="height: 40px">
                <!-- Spacing below header -->
            </div>
            <div id="content-top-border" class="container">
            </div>
            <!-- === END HEADER === -->
            <!-- === BEGIN CONTENT === -->
            <div id="content">
                <div class="container background-white">
                    <div class="row margin-vert-30">
                        <h1 class="formTitle">Add Destination</h1>
                        <div class="col-md-12 margin-top-30">
                            <!-- Place your form here -->

                            <form method="post" enctype="multipart/form-data" class="my-form mx-auto" style="max-width: 600px;">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="id_place_name">Place Name</label>
                                    {{ form.place_name }}
                                </div>
                                <div class="form-group">
                                    <label for="id_weather">Weather</label>
                                    {{ form.weather }}
                                </div>
                                <div class="form-group">
                                    <label for="id_state">State</label>
                                    {{ form.state }}
                                </div>
                                <div class="form-group">
                                    <label for="id_district">District</label>
                                    {{ form.district }}
                                </div>
                                <div class="form-group">
                                    <label for="id_location">Location</label>
                                    {{ form.google_map_link }}
                                </div>
                                <div class="form-group">
                                    <label for="id_description">Description</label>
                                    {{ form.description }}
                                </div>
                                <div class="form-group">
                                    <label for="id_image">Image</label>
                                    {{ form.image }}
                                </div>
                                <!-- Add more form fields as needed -->
                                <button type="submit" class="btn btn-primary d-block mx-auto">Submit</button>
                            </form>
                            
                            
                            <!-- End of form -->
                        </div>
                    </div>
                </div>
            </div>
            <!-- === END CONTENT === -->
            <!-- === BEGIN FOOTER === -->
            <div id="content-bottom-border" class="container">
            </div>
            <div id="base">
                <div class="container padding-vert-30 margin-top-60">
                    <div class="row">
                        <!-- Contact Details -->
                        <div class="col-md-4 margin-bottom-20">
                            <h3 class="margin-bottom-10">Contact Details</h3>
                            <p>
                                <span class="fa-phone">Telephone:</span>+91 7986881518
                                <br>
                                <span class="fa-envelope">Email:</span>
                                <a href=" {% static link to mail %} ">amalbennymnjt@gmail.com</a>
                                <br>
                                <span class="fa-link">Website:</span>
                                <a href="http://www.youridukki.com">http://www.trawell.com</a>
                            </p>
                            <p>Calvary Mount,
                                <br>Idukki,
                                <br>Kerala,
                                <br>India</p>
                        </div>
                        <!-- End Contact Details -->
                        <!-- Sample Menu -->
                        <div class="col-md-3 margin-bottom-20">
                            <h3 class="margin-bottom-10">Other Services</h3>
                            <ul class="menu">
                                <li>
                                    <a class="fa-tasks" href="#">Travel Booking</a>
                                </li>
                                <li>
                                    <a class="fa-users" href="#">Resorts</a>
                                </li>
                                <li>
                                    <a class="fa-signal" href="#">Room Booking</a>
                                </li>
                                <li>
                                    <a class="fa-coffee" href="#">Rent a Car</a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <!-- End Sample Menu -->
                        <div class="col-md-1"></div>
                        <!-- Disclaimer -->
                        <div class="col-md-3 margin-bottom-20 padding-vert-30 text-center">
                            <h3 class="color-gray margin-bottom-10">Join our Newsletter</h3>
                            <p>
                                Sign up for our newsletter for all the
                                <br>latest news and information
                            </p>
                            <input type="email">
                            <br>
                            <button class="btn btn-primary btn-lg margin-top-20" type="button">Subscribe</button>
                        </div>
                        <!-- End Disclaimer -->
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <!-- Footer Menu -->
            <div id="footer">
                <div class="container">
                    <div class="row">
                        <div id="copyright" class="col-md-4">
                            <p class="pull-right">2024 Amal Benny</p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Footer Menu -->
            <!-- JS -->
            <script type="text/javascript" src=" {% static 'assets/js/jquery.min.js' %} " type="text/javascript"></script>
            <script type="text/javascript" src=" {% static 'assets/js/bootstrap.min.js' %} " type="text/javascript"></script>
            <script type="text/javascript" src=" {% static 'assets/js/scripts.js' %} "></script>
            <!-- Isotope - Portfolio Sorting -->
            <script type="text/javascript" src=" {% static 'assets/js/jquery.isotope.js' %} " type="text/javascript"></script>
            <!-- Mobile Menu - Slicknav -->
            <script type="text/javascript" src=" {% static 'assets/js/jquery.slicknav.js' %} " type="text/javascript"></script>
            <!-- Animate on Scroll-->
            <script type="text/javascript" src=" {% static 'assets/js/jquery.visible.js' %} " charset="utf-8"></script>
            <!-- Sticky Div -->
            <script type="text/javascript" src=" {% static 'assets/js/jquery.sticky.js' %} " charset="utf-8"></script>
            <!-- Slimbox2-->
            <script type="text/javascript" src=" {% static 'assets/js/slimbox2.js' %} " charset="utf-8"></script>
            <!-- Modernizr -->
            <script src=" {% static 'assets/js/modernizr.custom.js' %} " type="text/javascript"></script>
            <!-- End JS -->
    </body>
</html>
<!-- === END FOOTER === -->

touristDestinations/templates/home.html
<!-- === BEGIN HEADER === -->
<!DOCTYPE html>
{% load static %}
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
    <!--<![endif]-->
    <head>
        <!-- Title -->
        <title>TRAWELL</title>
        <!-- Meta -->
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="description" content="">
        <meta name="author" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <!-- Favicon -->
        <link href=" {% static 'favicon.ico' %} " rel="shortcut icon">
        <!-- Bootstrap Core CSS -->
        <link rel="stylesheet" href=" {% static 'assets/css/bootstrap.css' %} " rel="stylesheet">
        <!-- Template CSS -->
        <link rel="stylesheet" href=" {% static 'assets/css/animate.css' %} " rel="stylesheet">
        <link rel="stylesheet" href=" {% static 'assets/css/font-awesome.css' %} " rel="stylesheet">
        <link rel="stylesheet" href=" {% static 'assets/css/nexus.css' %} " rel="stylesheet">
        <link rel="stylesheet" href=" {% static 'assets/css/responsive.css' %} " rel="stylesheet">
        <link rel="stylesheet" href=" {% static 'assets/css/custom.css' %} " rel="stylesheet">
        
        <link rel="stylesheet" href=" {% static 'assets/css/styles.css' %} " rel="stylesheet">
        <!-- Google Fonts-->
        <link href="http://fonts.googleapis.com/css?family=Roboto+Condensed:400,300" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=PT+Sans" type="text/css" rel="stylesheet">
        <link href="http://fonts.googleapis.com/css?family=Roboto:400,300" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div id="body-bg">
            <ul class="social-icons pull-right hidden-xs">
                <li class="social-rss">
                    <a href="https://www.instagram.com/_der_m.o.n.deur" target="_blank" title="RSS"></a>
                </li>
                <li class="social-twitter">
                    <a href="https://www.instagram.com/_der_m.o.n.deur" target="_blank" title="Twitter"></a>
                </li>
                <li class="social-facebook">
                    <a href="https://www.instagram.com/_der_m.o.n.deur" target="_blank" title="Facebook"></a>
                </li>
                <li class="social-googleplus">
                    <a href="https://www.instagram.com/_der_m.o.n.deur" target="_blank" title="GooglePlus"></a>
                </li>
            </ul>
            <div id="pre-header" class="container" style="height: 40px">
                <!-- Spacing above header -->
            </div>
            <div id="header">
                <div class="container">
                    <div class="row">
                        <!-- Logo -->
                        <div class="logo">
                            <a href=" {% static 'index.html' %} " title="">
                                <img src=" {% static 'assets/img/logo.png' %} " alt="Logo" />
                            </a>
                        </div>
                        <!-- End Logo -->
                    </div>
                </div>
            </div>
            <!-- Top Menu -->
            <div id="hornav" class="container no-padding">
                <div class="row">
                    <div class="col-md-12 no-padding">
                        <div class="text-center visible-lg">
                            <ul id="hornavmenu" class="nav navbar-nav">
                                <li>
                                    <a href="" class="fa-home">Home</a>
                                </li>
                                <li>
                                    <span class="fa-gears">Locations</span>
                                    <ul>
                                        <li class="parent">
                                            <span>Trawell</span>
                                            <ul>
                                                <li>
                                                    <a href="read">Explore</a>
                                                </li>
                                                <li>
                                                    <a href="read">Our Packages</a>
                                                </li>
                                            </ul>
                                        </li>
                                        
                                </li>
                                <li>
                                    <span class="fa-th">Add a Spot</span>
                                    <ul>
                                        <li>
                                            <a href="create">Add a Spot to our list</a>
                                        </li>
                                    
                                    </ul>
                                </li>
                                <li>
                                    <span class="fa-font">Update Details</span>
                                    <ul>
                                        <li>
                                            <a href="read">Edit details</a>
                                        </li>
                                        
                                    </ul>
                                </li>
                                <li>
                                    <a href="read" class="fa-comment">View the Locations</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Top Menu -->
            <div id="post_header" class="container" style="height: 40px">
                <!-- Spacing below header -->
            </div>
            <div id="content-top-border" class="container">
            </div>
            <!-- === END HEADER === -->
            <!-- === BEGIN CONTENT === -->
            <div id="content">
                <div class="container background-white">
                    <div class="row margin-vert-30">
                        <div class="col-md-12 margin-top-30">
                            <!-- Place your form here -->

                            <img src=" {% static 'assets/img/bg.png' %} ">


                            <!-- End of form -->
                        </div>
                    </div>
                </div>
            </div>
            <!-- === END CONTENT === -->
            <!-- === BEGIN FOOTER === -->
            <div id="content-bottom-border" class="container">
            </div>
            <div id="base">
                <div class="container padding-vert-30 margin-top-60">
                    <div class="row">
                        <!-- Contact Details -->
                        <div class="col-md-4 margin-bottom-20">
                            <h3 class="margin-bottom-10">Contact Details</h3>
                            <p>
                                <span class="fa-phone">Telephone:</span>+91 7986881518
                                <br>
                                <span class="fa-envelope">Email:</span>
                                <a href=" {% static link to mail %} ">amalbennymnjt@gmail.com</a>
                                <br>
                                <span class="fa-link">Website:</span>
                                <a href="http://www.youridukki.com">http://www.trawell.com</a>
                            </p>
                            <p>Calvary Mount,
                                <br>Idukki,
                                <br>Kerala,
                                <br>India</p>
                        </div>
                        <!-- End Contact Details -->
                        <!-- Sample Menu -->
                        <div class="col-md-3 margin-bottom-20">
                            <h3 class="margin-bottom-10">Other Services</h3>
                            <ul class="menu">
                                <li>
                                    <a class="fa-tasks" href="#">Travel Booking</a>
                                </li>
                                <li>
                                    <a class="fa-users" href="#">Resorts</a>
                                </li>
                                <li>
                                    <a class="fa-signal" href="#">Room Booking</a>
                                </li>
                                <li>
                                    <a class="fa-coffee" href="#">Rent a Car</a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <!-- End Sample Menu -->
                        <div class="col-md-1"></div>
                        <!-- Disclaimer -->
                        <div class="col-md-3 margin-bottom-20 padding-vert-30 text-center">
                            <h3 class="color-gray margin-bottom-10">Join our Newsletter</h3>
                            <p>
                                Sign up for our newsletter for all the
                                <br>latest news and information
                            </p>
                            <input type="email">
                            <br>
                            <button class="btn btn-primary btn-lg margin-top-20" type="button">Subscribe</button>
                        </div>
                        <!-- End Disclaimer -->
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
            <!-- Footer Menu -->
            <div id="footer">
                <div class="container">
                    <div class="row">
                        <div id="copyright" class="col-md-4">
                            <p class="pull-right">2024 Amal Benny</p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End Footer Menu -->
            <!-- JS -->
            <script type="text/javascript" src=" {% static 'assets/js/jquery.min.js' %} " type="text/javascript"></script>
            <script type="text/javascript" src=" {% static 'assets/js/bootstrap.min.js' %} " type="text/javascript"></script>
            <script type="text/javascript" src=" {% static 'assets/js/scripts.js' %} "></script>
            <!-- Isotope - Portfolio Sorting -->
            <script type="text/javascript" src=" {% static 'assets/js/jquery.isotope.js' %} " type="text/javascript"></script>
            <!-- Mobile Menu - Slicknav -->
            <script type="text/javascript" src=" {% static 'assets/js/jquery.slicknav.js' %} " type="text/javascript"></script>
            <!-- Animate on Scroll-->
            <script type="text/javascript" src=" {% static 'assets/js/jquery.visible.js' %} " charset="utf-8"></script>
            <!-- Sticky Div -->
            <script type="text/javascript" src=" {% static 'assets/js/jquery.sticky.js' %} " charset="utf-8"></script>
            <!-- Slimbox2-->
            <script type="text/javascript" src=" {% static 'assets/js/slimbox2.js' %} " charset="utf-8"></script>
            <!-- Modernizr -->
            <script src=" {% static 'assets/js/modernizr.custom.js' %} " type="text/javascript"></script>
            <!-- End JS -->
    </body>
</html>
<!-- === END FOOTER === -->